---
title: "descriptive"
author: "A.Amstutz"
date: "2023-12-29"
output:
  html_document:
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
  pdf_document:
    toc: true
  word_document:
    toc: true
---

# Load packages
```{r load packages, echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(writexl)
library(tableone)
library(data.table)
library(here)
library(kableExtra)
```

# Load entire dataset (from one-stage.Rmd)
## Make sure to run one-stage before
```{r echo=TRUE}
df_tot <- readRDS("df_tot.RData") # without Murugesan
# df_tot_Muru <- readRDS("df_tot_Muru.RData") # with Murugesan
```

## Baseline characteristics, reformatting
```{r message=FALSE, warning=FALSE}
vars.list <- c("trt", "trial", "age", "sex", "ethn", "country", "vacc", "sympdur", "icu", "clinstatus_baseline", "comorb_cat", "comed_cat", "comed_rdv", "crp", "sero", "vl_baseline")

df_baseline <- df_tot[,colnames(df_tot)%in%vars.list]
df_baseline <- df_baseline[,match(vars.list,colnames(df_baseline))]

colnames(df_baseline) <- vars.list <- c("ARM","Trial","Age, years", "Sex", "Ethnicity", "Country", "Vaccination", "Time from symptom onset to randomisation, days", "Patients admitted to intensive care unit","Clinical status on ordinal scale", "Comorbidities", "Dexamethasone and Tocilizumab", "Remdesivir","C-reactive protein concentration, mg/L", "Seroconversion (patients with detectable anti-SARS-CoV-2 antibodies [anti-RBD or anti-N])", "Patients with undetectable viral load")

char_vars <- c("Trial","Sex", "Ethnicity", "Country", "Vaccination","Patients admitted to intensive care unit","Clinical status on ordinal scale","Comorbidities", "Dexamethasone and Tocilizumab", "Remdesivir","Seroconversion (patients with detectable anti-SARS-CoV-2 antibodies [anti-RBD or anti-N])", "Patients with undetectable viral load")

# Convert character variables to factors
df_baseline <- df_baseline %>%
  mutate(across(all_of(char_vars), factor))


# Sex
# unique(df_baseline$Sex)
df_baseline <- df_baseline %>%
  mutate(Sex = case_when(Sex == "male" | Sex == "M" | Sex == "2" ~ "Male",
                         Sex == "female" | Sex == "F" | Sex == "1" ~ "Female"))

# Ethnicity
# table(df_baseline$Ethnicity, useNA = "always")
df_baseline <- df_baseline %>%
  mutate(Ethnicity = case_when(Ethnicity == "AMERICAN INDIAN OR ALASKA NATIVE" ~ "American Indian or Alaska Native",
                             Ethnicity == "BLACK OR AFRICAN AMERICAN" | Ethnicity == "Black or Black British" ~ "Black or African American",
                             Ethnicity == "Asian" | Ethnicity == "ASIAN" | Ethnicity == "Asian or Asian British" ~ "Asian",
                             Ethnicity == "caucasian" | Ethnicity == "White" | Ethnicity == "WHITE" ~ "Caucasian",
                             Ethnicity == "HISPANIC OR LATINO" | Ethnicity == "Latino" ~ "Hispanic or Latino",
                             Ethnicity == "MIXED" | Ethnicity == "Mixed" | Ethnicity == "MULTIPLE" ~ "Mixed",
                             Ethnicity == "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER" ~ "Native Hawaiian or other Pacific Islander",
                             Ethnicity == "Persian/Mazani" ~ "Persian/Mazani"))


# Country
# table(df_baseline$Country, useNA = "always")
df_baseline <- df_baseline %>%
  mutate(Country = case_when(Country == "NORWAY" ~ "Norway",
                             Country == "FRANCE" ~ "France",
                             Country == "ITA" | Country == "ITALY" | Country == "Italy" ~ "Italy",
                             Country == "Iran" ~ "Iran",
                             Country == "GERMANY" | Country == "DEU" ~ "Germany",
                             Country == "SPAIN" | Country == "ESP" | Country == "Spain" ~ "Spain",
                             Country == "BELGIUM" ~ "Belgium",
                             Country == "PORTUGAL" ~ "Portugal",
                             Country == "IRELAND" ~ "Ireland",
                             Country == "LUXEMBOURG" ~ "Luxembourg",
                             Country == "AUSTRIA" ~ "Austria",
                             Country == "GBR" ~ "United Kingdom",
                             Country == "PORTUGAL" ~ "Portugal",
                             Country == "MEX" ~ "Mexico",
                             Country == "ARG" ~ "Argentina",
                             Country == "BRA" ~ "Brasil",
                             Country == "RUS" ~ "Russia",
                             Country == "JPN" ~ "Japan",
                             Country == "KOR" ~ "South Korea",
                             Country == "IND" ~ "India",
                             Country == "USA" ~ "USA",
                             Country == "Asia" ~ "Asia*",
                             Country == "Europe" ~ "Europe*",
                             Country == "North America" ~ "North America*"
                             ))

# Vaccination
df_baseline <- df_baseline %>%
  mutate(Vaccination = case_when(Vaccination == "1" ~ "Any SARS CoV-2 vaccine",
                                Vaccination == "0" ~ "No SARS CoV-2 vaccine"))
# ICU
df_baseline <- df_baseline %>%
  mutate(`Patients admitted to intensive care unit` = case_when(`Patients admitted to intensive care unit` == "1" ~ "Yes",
                                                                `Patients admitted to intensive care unit` == "0" ~ "No"))
# Comorbidities
df_baseline <- df_baseline %>%
  mutate(Comorbidities = case_when(Comorbidities == "1" ~ "No comorbidity",
                                   Comorbidities == "2" ~ "One comorbidity",
                                   Comorbidities == "3" ~ "Multiple comorbidities",
                                   Comorbidities == "4" ~ "Immunocompromised"))
df_baseline$Comorbidities <- ordered(df_baseline$Comorbidities,
                                  levels = c("No comorbidity", "One comorbidity",
                                             "Multiple comorbidities", "Immunocompromised"))
# Dexamethasone and Tocilizumab
df_baseline <- df_baseline %>%
  mutate(`Dexamethasone and Tocilizumab` = case_when(`Dexamethasone and Tocilizumab` == "1" ~ "No Dexamethasone, no Tocilizumab",
                                   `Dexamethasone and Tocilizumab` == "2" ~ "Dexamethasone and Tocilizumab",
                                   `Dexamethasone and Tocilizumab` == "3" ~ "Dexamethasone but no Tocilizumab",
                                  `Dexamethasone and Tocilizumab` == "4" ~ "Tocolizumab but no Dexamethasone"))
df_baseline$`Dexamethasone and Tocilizumab` <- ordered(df_baseline$`Dexamethasone and Tocilizumab`,
                                  levels = c("No Dexamethasone, no Tocilizumab", "Dexamethasone but no Tocilizumab",
                                             "Dexamethasone and Tocilizumab", "Tocolizumab but no Dexamethasone"))

# Clinstatus_baseline
df_baseline <- df_baseline %>%
  mutate(`Clinical status on ordinal scale` = case_when(`Clinical status on ordinal scale` == "2" ~ "2: Hospitalised without need for oxygen therapy (WHO score 4)",
                                   `Clinical status on ordinal scale` == "3" ~ "3: Hospitalised with need for supplemental low-flow oxygen (WHO score 5)",
                                   `Clinical status on ordinal scale` == "4" ~ "4: Hospitalised with need for high-flow oxygen or non- invasive ventilation (WHO score 6)",
                                  `Clinical status on ordinal scale` == "5" ~ "5: Hospitalised with need for mechanical ventilation or ECMO (WHO score 7–9)"))

df_baseline$`Clinical status on ordinal scale` <- ordered(df_baseline$`Clinical status on ordinal scale`,
                                  levels = c("2: Hospitalised without need for oxygen therapy (WHO score 4)", "3: Hospitalised with need for supplemental low-flow oxygen (WHO score 5)", "4: Hospitalised with need for high-flow oxygen or non- invasive ventilation (WHO score 6)", "5: Hospitalised with need for mechanical ventilation or ECMO (WHO score 7–9)"))

# Remdesivir
df_baseline <- df_baseline %>%
  mutate(Remdesivir = case_when(Remdesivir == "1" ~ "Remdesivir",
                                Remdesivir == "0" ~ "No Remdesivir"))
# Seroconversion
df_baseline <- df_baseline %>%
  mutate(`Seroconversion (patients with detectable anti-SARS-CoV-2 antibodies [anti-RBD or anti-N])` = case_when(`Seroconversion (patients with detectable anti-SARS-CoV-2 antibodies [anti-RBD or anti-N])` == "1" ~ "Seroconverted",
                                `Seroconversion (patients with detectable anti-SARS-CoV-2 antibodies [anti-RBD or anti-N])` == "0" ~ "Not seroconverted"))
# Viremia
df_baseline <- df_baseline %>%
  mutate(`Patients with undetectable viral load` = case_when(`Patients with undetectable viral load` == "1" ~ "Undetectable viral load",
                                `Patients with undetectable viral load` == "0" ~ "Detectable viral load"))

# Replace the strata variable labels
df_baseline$ARM <- ifelse(df_baseline$ARM == 0, "No JAK inhibitor", "JAK inhibitor")

```

# Main Baseline table, by treatment arm
```{r message=FALSE, warning=FALSE}
vars.list_main <- c("ARM","Age, years", "Sex", "Vaccination", "Time from symptom onset to randomisation, days", "Clinical status on ordinal scale", "Comorbidities", "Dexamethasone and Tocilizumab", "Remdesivir", "C-reactive protein concentration, mg/L", "Seroconversion (patients with detectable anti-SARS-CoV-2 antibodies [anti-RBD or anti-N])", "Patients with undetectable viral load")
table_baseline <- CreateTableOne(data = df_baseline, vars = vars.list_main[!vars.list_main %in% c("ARM")], strata = "ARM", includeNA = F, test = F, addOverall = TRUE)
capture.output(table_baseline <- print(table_baseline, nonnormal = vars.list_main,catDigits = 1,SMD = TRUE,showAllLevels = TRUE,test = TRUE,printToggle = FALSE,missing = TRUE))
# print
kable(table_baseline, format = "markdown", table.attr = 'class="table"', caption = "Main Baseline characteristics, by arm") %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)
```

# Appendix Baseline table, by treatment arm
```{r message=FALSE, warning=FALSE}
vars.list_appendix <- c("ARM", "Ethnicity", "Country", "Patients admitted to intensive care unit")
table_baseline <- CreateTableOne(data = df_baseline, vars = vars.list_appendix[!vars.list_appendix %in% c("ARM")], strata = "ARM", includeNA = F, test = F, addOverall = TRUE)
capture.output(table_baseline <- print(table_baseline, nonnormal = vars.list_appendix,catDigits = 1,SMD = TRUE,showAllLevels = TRUE,test = TRUE,printToggle = FALSE,missing = TRUE))
# print
kable(table_baseline, format = "markdown", table.attr = 'class="table"', caption = "Appendix Baseline characteristics, by arm") %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)
```


# All Baseline Characteristics, by trial
```{r message=FALSE, warning=FALSE}
# all participants, by trial
table_baseline_trial <- CreateTableOne(data = df_baseline, vars = vars.list[!vars.list %in% c("Trial", "ARM")], strata = "Trial", includeNA = F, test = F, addOverall = TRUE)
capture.output(table_baseline_trial <- print(table_baseline_trial, nonnormal = vars.list,catDigits = 1,SMD = TRUE,showAllLevels = TRUE,test = TRUE,printToggle = FALSE,missing = TRUE))
#print
kable(table_baseline_trial, format = "markdown", table.attr = 'class="table"', caption = "Baseline characteristics, by trial") %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)
```


# Missing data table for outcomes and adjustment variables, by trial
```{r message=FALSE, warning=FALSE}
vars.list <- c("trial", "age", "clinstatus_baseline",
               "mort_28", "mort_60", "new_mvd_28", "clinstatus_28_imp", 
                "ae_28", "vir_clear_5" ,"vir_clear_10", "vir_clear_15")
df_missing <- df_tot[,colnames(df_tot)%in%vars.list]
df_missing <- df_missing[,match(vars.list,colnames(df_missing))]

# Count missing values for each variable within each trial, and its proportion
age_missing_summary <- df_missing %>%
  group_by(trial) %>%
  summarise(across(starts_with("age"), list(
    count_missing = ~ sum(is.na(.)),
    denominator = ~ n(),
    prop_missing = ~ round(sum(is.na(.)) / n(), 3) * 100
  ))) %>%
  unite("age_summary", starts_with("age"), sep = "/", na.rm = TRUE) 

clinstatus_baseline_missing_summary <- df_missing %>%
  group_by(trial) %>%
  summarise(across(starts_with("clinstatus_baseline"), list(
    count_missing = ~ sum(is.na(.)),
    denominator = ~ n(),
    prop_missing = ~ round(sum(is.na(.)) / n(), 3) * 100
  ))) %>%
  unite("clinstatus_baseline_summary", starts_with("clinstatus_baseline"), sep = "/", na.rm = TRUE) 

mort_28_missing_summary <- df_missing %>%
  group_by(trial) %>%
  summarise(across(starts_with("mort_28"), list(
    count_missing = ~ sum(is.na(.)),
    denominator = ~ n(),
    prop_missing = ~ round(sum(is.na(.)) / n(), 3) * 100
  ))) %>%
  unite("mort_28_summary", starts_with("mort_28"), sep = "/", na.rm = TRUE) 

mort_60_missing_summary <- df_missing %>%
  group_by(trial) %>%
  summarise(across(starts_with("mort_60"), list(
    count_missing = ~ sum(is.na(.)),
    denominator = ~ n(),
    prop_missing = ~ round(sum(is.na(.)) / n(), 3) * 100
  ))) %>%
  unite("mort_60_summary", starts_with("mort_60"), sep = "/", na.rm = TRUE) 

new_mvd_28_missing_summary <- df_missing %>%
  group_by(trial) %>%
  summarise(across(starts_with("new_mvd_28"), list(
    count_missing = ~ sum(is.na(.)),
    denominator = ~ n(),
    prop_missing = ~ round(sum(is.na(.)) / n(), 3) * 100
  ))) %>%
  unite("new_mvd_28_summary", starts_with("new_mvd_28"), sep = "/", na.rm = TRUE) 

clinstatus_28_imp_missing_summary <- df_missing %>%
  group_by(trial) %>%
  summarise(across(starts_with("clinstatus_28_imp"), list(
    count_missing = ~ sum(is.na(.)),
    denominator = ~ n(),
    prop_missing = ~ round(sum(is.na(.)) / n(), 3) * 100
  ))) %>%
  unite("clinstatus_28_imp_summary", starts_with("clinstatus_28_imp"), sep = "/", na.rm = TRUE) 

ae_28_missing_summary <- df_missing %>%
  group_by(trial) %>%
  summarise(across(starts_with("ae_28"), list(
    count_missing = ~ sum(is.na(.)),
    denominator = ~ n(),
    prop_missing = ~ round(sum(is.na(.)) / n(), 3) * 100
  ))) %>%
  unite("ae_28_summary", starts_with("ae_28"), sep = "/", na.rm = TRUE) 

vir_clear_5_missing_summary <- df_missing %>%
  group_by(trial) %>%
  summarise(across(starts_with("vir_clear_5"), list(
    count_missing = ~ sum(is.na(.)),
    denominator = ~ n(),
    prop_missing = ~ round(sum(is.na(.)) / n(), 3) * 100
  ))) %>%
  unite("vir_clear_5_summary", starts_with("vir_clear_5"), sep = "/", na.rm = TRUE) 

vir_clear_10_missing_summary <- df_missing %>%
  group_by(trial) %>%
  summarise(across(starts_with("vir_clear_10"), list(
    count_missing = ~ sum(is.na(.)),
    denominator = ~ n(),
    prop_missing = ~ round(sum(is.na(.)) / n(), 3) * 100
  ))) %>%
  unite("vir_clear_10_summary", starts_with("vir_clear_10"), sep = "/", na.rm = TRUE) 

vir_clear_15_missing_summary <- df_missing %>%
  group_by(trial) %>%
  summarise(across(starts_with("vir_clear_15"), list(
    count_missing = ~ sum(is.na(.)),
    denominator = ~ n(),
    prop_missing = ~ round(sum(is.na(.)) / n(), 3) * 100
  ))) %>%
  unite("vir_clear_15_summary", starts_with("vir_clear_15"), sep = "/", na.rm = TRUE) 

missing_summary <- cbind(age_missing_summary, clinstatus_baseline_missing_summary, mort_28_missing_summary, mort_60_missing_summary, new_mvd_28_missing_summary, clinstatus_28_imp_missing_summary, ae_28_missing_summary, vir_clear_5_missing_summary, vir_clear_10_missing_summary, vir_clear_15_missing_summary)

missing_summary <- missing_summary %>% select(1 | ends_with("_summary"))

#print
kable(missing_summary, format = "markdown", table.attr = 'class="table"', caption = "Missing values in outcomes and adjustment variables, by trial") %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)

```

# Missing data table for all variables, by trial
```{r message=FALSE, warning=FALSE}
table(df_tot$mort_28,useNA = "always")

vars.list <- c("trt", "trial", "age", "sex", "ethn", "country", "vacc", "sympdur", "icu", "clinstatus_baseline", "comorb_cat", "comed_cat", "comed_rdv", "crp", "sero", "vl_baseline", "variant",
               "mort_28", "mort_60", "death_reached", "new_mv_28", "new_mvd_28", "clinstatus_28_imp", "discharge_reached",
               "discharge_reached_sus" , "ae_28","ae_28_sev" ,"vir_clear_5" ,"vir_clear_10", "vir_clear_15")

df_missing <- df_tot[,colnames(df_tot)%in%vars.list]
df_missing <- df_missing[,match(vars.list,colnames(df_missing))]

# colnames(df_missing) <- vars.list <- c("ARM","Trial","Age, years", "Sex", "Ethnicity", "Country", "Vaccinated", "Time from symptom onset to randomisation, days", "Patients admitted to intensive care unit","Clinical status on ordinal scale", "Comorbidities", "Dexamethasone and Tocilizumab", "Remdesivir","C-reactive protein concentration, mg/L", "Seroconversion (patients with detectable anti-SARS-CoV-2 antibodies [anti-RBD or anti-N])", "Patients with detectable viral load", "SARS CoV-2 variant")

char_vars <- c("trt", "trial", "sex", "ethn", "country", "vacc", "icu", "clinstatus_baseline", "comorb_cat", "comed_cat", "comed_rdv", "sero", "vl_baseline", "variant",
               "mort_28", "mort_60", "death_reached", "new_mv_28", "new_mvd_28", "clinstatus_28_imp", "discharge_reached",
               "discharge_reached_sus" , "ae_28","ae_28_sev" ,"vir_clear_5" ,"vir_clear_10", "vir_clear_15")

# Convert character variables to factors
df_missing <- df_missing %>%
  mutate(across(all_of(char_vars), factor))

# all missing data, by trial
table_missing_trial <- CreateTableOne(data = df_missing, vars = vars.list[!vars.list %in% c("trt", "trial")], strata = "trial", includeNA = T, test = F, addOverall = TRUE)
capture.output(table_missing_trial <- print(table_missing_trial, nonnormal = vars.list,catDigits = 1,SMD = TRUE,showAllLevels = TRUE,test = TRUE,printToggle = FALSE,missing = TRUE))
#print
kable(table_missing_trial, format = "markdown", table.attr = 'class="table"', caption = "Missing data, by trial") %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)

```
