---
title: "TACTIC-R"
author: "A.Amstutz"
date: "2024-04-12"
output:
  html_document:
    keep_md: yes
    toc: yes
    toc_float: yes
    code_folding: hide
  pdf_document:
    toc: yes
---

# Load packages
```{r load packages, echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(writexl)
library(tableone)
library(haven) # Read sas files
library(here)
library(kableExtra)

library(jtools) # for summ() and plot_summs
library(sjPlot) # for tab_model
library(ggplot2) # survival/TTE analyses and other graphs
library(ggsurvfit) # survival/TTE analyses
library(survival) # survival/TTE analyses
library(gtsummary) # survival/TTE analyses
library(ggfortify) # autoplot
library(tidycmprsk) # competing risk analysis
library(ordinal) # clinstatus ordinal regression
library(logistf) # Firth regression in case of rare events

library(finalfit) # missing data exploration
library(mice) # multiple imputation
library(jomo) # multiple imputation
library(mitools) # multiple imputation

```

# Load Data
```{r, include=FALSE}
df <- read_csv("/Users/amstutzal/Library/CloudStorage/OneDrive-usb.ch/Dokumente - JAKi IPDMA data source management/General/TACTIC-R/TACTIC_R20240409_SCRN_to_DAY10.csv")
df2 <- read_csv("/Users/amstutzal/Library/CloudStorage/OneDrive-usb.ch/Dokumente - JAKi IPDMA data source management/General/TACTIC-R/TACTIC_R20240409_DAY11_to_UNSCHEDULEDVISIT.csv")
```

# Baseline Characteristics
```{r echo=TRUE, message=FALSE, warning=FALSE}
# dataframe 2, only data from those who were randomised, but long format, for each form/entry/record
# df2 <- df2 %>% # fill up NA / CAVE: does not correspond with PersonID and Label, rather use Label instead and extract id from it
#   fill(SUBJID_DER)
df2$id_pat <- sub(".*N(\\d+).*", "\\1", df2$Label)
# df2 <- df2 %>% 
#   select(id_pat, SUBJID_DER, SUBJID_DER122, PersonId, DATE_DEATH, Label, everything())
num_unique_id_pat <- length(unique(df2$id_pat)) # correct, 282 unique IDs, as per publication in Bari + SOC group and as dataframe 1

# dataframe 1, only with those who were randomised (n=282), but wide format (282 rows)
df <- df %>% rename(id_pat = SUBJID)
df <- df %>% # randomization variable, see codebook
  mutate(trt = case_when(RANDOM_TREAT == 2 ~ 1,
                         RANDOM_TREAT == 3 ~ 0))
df$trial <- "TACTIC-R"
df$JAKi <- "Baricitinib"
df$country <- "UK"
df$randdate <- as.Date(df$RANDOM_DATE, format = "%d/%m/%Y") # randomisation date

# Sex
df <- df %>% # Corresponds to publication
  mutate(sex = case_when(DEMO_SEX == 1 ~ "male",
                         DEMO_SEX == 2 ~ "female")) %>% # if missing, use info from risk score
  mutate(sex = case_when(is.na(sex) & RISK_MALEGEN == 1 ~ "male",
                         is.na(sex) & RISK_MALEGEN == 0 ~ "female",
                         TRUE ~ sex))
# Ethnicity
df <- df %>% # Corresponds to publication
  mutate(ethn = case_when(DEMO_ETHNIC == 1 ~ "White",
                          DEMO_ETHNIC == 2 ~ "Mixed",
                          DEMO_ETHNIC == 3 ~ "Asian or Asian British",
                          DEMO_ETHNIC == 4 ~ "Black or Black British",
                          DEMO_ETHNIC == 5 ~ "Other")) %>% # if missing, use info from risk score
  mutate(ethn = case_when(is.na(ethn) & RISK_NONWHITE == 0 ~ "White", 
                          TRUE ~ ethn)) %>% # if still missing, use info from DEMO_ETHNIC1
  mutate(ethn = case_when(is.na(ethn) & DEMO_ETHNIC1 == 1 ~ "White",
                          is.na(ethn) & DEMO_ETHNIC1 == 2 ~ "Mixed",
                          is.na(ethn) & DEMO_ETHNIC1 == 3 ~ "Asian or Asian British",
                          is.na(ethn) & DEMO_ETHNIC1 == 4 ~ "Black or Black British",
                          is.na(ethn) & DEMO_ETHNIC1 == 5 ~ "Other",
                          TRUE ~ ethn))

# AGE
df <- df %>% # Corresponds to publication
  mutate(age = as.numeric(df$DEMO_AGE)) %>% # if missing, use info from derived age
  mutate(age = case_when(is.na(age) & !is.na(DERIVE_AGE) ~ as.numeric(DERIVE_AGE), 
                          TRUE ~ age))
# df %>% 
#   filter(trt == 1) %>%
#   select(age) %>% 
#   summary()
df %>%
  ggplot(aes(x = age)) +
  geom_density(fill = "blue", color = "black") +
  labs(title = "Density Plot of Age",
       x = "Age",
       y = "Density")


### Days with symptoms prior to randomization
df$sympdur_date <- as.Date(df$ONSET_FIRSTD, format = "%d/%m/%Y") # randomisation date
df <- df %>% 
  mutate(sympdur = randdate - sympdur_date)
df %>% 
  drop_na(sympdur) %>% 
  ggplot(aes(x = sympdur)) +
  geom_density(fill = "blue", color = "black") +
  labs(title = "Density Plot of Symptom Duration",
       x = "Symptom Duration",
       y = "Density")


### Clinical score at baseline

# POINT7_OS_POS	1	Death
# POINT7_OS_POS	2	Invasive mechanical ventilation
# POINT7_OS_POS	3	Non-invasive ventilation or high flow oxygen
# POINT7_OS_POS	4	Low flow oxygen
# POINT7_OS_POS	5	Hospitalised, no oxygen
# POINT7_OS_POS	6	Discharged, normal activities not resumed
# POINT7_OS_POS	7	Discharged, normal activities resumed

# double-check with the following for the follow-up scores since always in parallel (not for baseline, since this was collected during pre-screening, while the ordinal score was at randomization):

# RESP_DELIVER	1	Nasal cannula
# RESP_DELIVER	2	Venturi mask
# RESP_DELIVER	3	Ambu or rebreathing bag
# RESP_DELIVER	4	Non-invasive ventilation
# RESP_DELIVER	5	Continuous positive airway pressure (CPAP)
# RESP_DELIVER	6	Extracorporeal membrane oxygenation (ECMO)
# RESP_DELIVER	7	Invasive mechanical ventilation

# directly translatable into our score:
df <- df %>% # Corresponds to publication
  mutate(clinstatus_baseline = case_when(POINT7_OS_POS == 1 ~ 6,
                                         POINT7_OS_POS == 2 ~ 5,
                                         POINT7_OS_POS == 3 ~ 4,
                                         POINT7_OS_POS == 4 ~ 3,
                                         POINT7_OS_POS == 5 ~ 2,
                                         POINT7_OS_POS == 6 ~ 1,
                                         POINT7_OS_POS == 7 ~ 1))

### Co-medication at baseline
## DEXA/CORTICO
df_dexa <- df2 %>%
  filter(grepl("dexa|cort|glucoc|hydrocor|predn|solon|methyl|Neofordex|Glensoludex|Martapan", CM_NAME, ignore.case = TRUE) &
         !grepl("Dexafree|fludro|symb|pul|dakta|penici", CM_NAME, ignore.case = TRUE)) # exclude Dexafree, fludrocortisone, symbi/pulmicort, daktacort, Phenoxymethylpenicillin 
# unique(df_dexa$CM_NAME)

# exclude non-baseline medication and unsuitable dexa equivalents (e.g. see NIH guidelines):
# If dexamethasone is not available, alternative corticosteroids (e.g., prednisone, methylprednisolone, hydrocortisone) can be used, For these drugs, the total daily dose equivalencies to dexamethasone 6 mg (orally or intravenously) are:
# Prednisone 40 mg
# Methylprednisolone 32 mg
# Hydrocortisone 160 mg

df_dexa <- left_join(df_dexa, df[, c("randdate", "trt", "id_pat")], by = join_by(id_pat == id_pat))
df_dexa$cm_start_date <- as.Date(df_dexa$CM_START, format = "%d/%m/%Y") 
# df_dexa %>%
#   select(id_pat, SUBJID_DER1, SUBJID_DER2, SUBJID_DER3, CM_NAME, CM_DOSE, CMDOSU, CM_FREQ, CM_FREQ_OTH, CM_ROUTE, CMROUTEOTH, CM_START, CM_END, randdate, cm_start_date, trt) %>%
#   View()
df_dexa <- df_dexa %>% 
  mutate(cm_baseline = case_when(cm_start_date <= randdate + 1 ~ 1, TRUE ~ 0)) %>% 
  filter(cm_baseline == 1) %>% # only those with steroid use at baseline + 1 day or before
  filter(!(CM_NAME == "Prednisolone" & CM_DOSE == 1)) %>% # exclude low-dose predni, medical history medication
  filter(!(CM_NAME == "Prednislone" & CM_DOSE == 3)) %>%  # exclude low-dose predni, medical history medication
  distinct(id_pat) %>% # only 1 entry per patient
  mutate(comed_dexa = 1)
df <- left_join(df, df_dexa[, c("comed_dexa", "id_pat")], by = join_by(id_pat == id_pat)) # merge to main df
df <- df %>% 
  mutate(comed_dexa = case_when(is.na(comed_dexa) ~ 0,
                          TRUE ~ comed_dexa))
# addmargins(table(df$comed_dexa, df$trt, useNA = "always")) # corresponds closely to trial publication Table 1 but they show use over entire study period 

# REMDESIVIR
# REMDES_TRT_ENR & REMDES_TRT_ENR1 do not help, instead use info from concomitant medication forms
# unique(df2$CM_NAME)
df_rdv <- df2 %>%
  filter(grepl("rem|rdv|veklury|vek|klur", CM_NAME, ignore.case = TRUE))
# unique(df_rdv$CM_NAME)
df_rdv <- left_join(df_rdv, df[, c("randdate", "trt", "id_pat")], by = join_by(id_pat == id_pat))
df_rdv$cm_start_date <- as.Date(df_rdv$CM_START, format = "%d/%m/%Y") 
df_rdv <- df_rdv %>% 
  mutate(cm_baseline = case_when(cm_start_date <= randdate + 1 ~ 1, TRUE ~ 0)) %>% 
  filter(cm_baseline == 1) %>% # only those with use at baseline + 1 day or before
  distinct(id_pat) %>% # only 1 entry per patient
  mutate(comed_rdv = 1)
df <- left_join(df, df_rdv[, c("comed_rdv", "id_pat")], by = join_by(id_pat == id_pat)) # merge to main df
df <- df %>% 
  mutate(comed_rdv = case_when(is.na(comed_rdv) ~ 0,
                          TRUE ~ comed_rdv))
# addmargins(table(df$comed_rdv, df$trt, useNA = "always")) # corresponds closely to trial publication Table 1 but they show use over entire study period 

# TOCILIZUMAB and other IL-6 inhibitors
# unique(df2$CM_NAME)
df_toci <- df2 %>%
  filter(grepl("toc|toz|sari|zumab|actem|kevzara", CM_NAME, ignore.case = TRUE) & 
           !grepl("tocopher|metoc", CM_NAME, ignore.case = TRUE)) # exclude Alphatocopherol & Metoclopromide
# unique(df_toci$CM_NAME)
df_toci <- left_join(df_toci, df[, c("randdate", "trt", "id_pat")], by = join_by(id_pat == id_pat))
df_toci$cm_start_date <- as.Date(df_toci$CM_START, format = "%d/%m/%Y") 
df_toci <- df_toci %>% 
  mutate(cm_baseline = case_when(cm_start_date <= randdate + 1 ~ 1, TRUE ~ 0)) %>% 
  filter(cm_baseline == 1) %>% # only those with use at baseline + 1 day or before
  distinct(id_pat) %>% # only 1 entry per patient
  mutate(comed_toci = 1)
df <- left_join(df, df_toci[, c("comed_toci", "id_pat")], by = join_by(id_pat == id_pat)) # merge to main df
df <- df %>% 
  mutate(comed_toci = case_when(is.na(comed_toci) ~ 0,
                          TRUE ~ comed_toci))
# addmargins(table(df$comed_toci, df$trt, useNA = "always")) # corresponds closely to trial publication Table 1 since they show use over entire study period 

# ANTICOAGULATION
df_acoa <- df2 %>%
  filter(grepl("coag|hepar|LMWH|UFH|parin|fragmin|lovenox|innohep|clexa", CM_NAME, ignore.case = TRUE))
# unique(df_acoa$CM_NAME)
df_acoa <- left_join(df_acoa, df[, c("randdate", "trt", "id_pat")], by = join_by(id_pat == id_pat))
df_acoa$cm_start_date <- as.Date(df_acoa$CM_START, format = "%d/%m/%Y") 
df_acoa <- df_acoa %>% 
  mutate(cm_baseline = case_when(cm_start_date <= randdate + 1 ~ 1, TRUE ~ 0)) %>% 
  filter(cm_baseline == 1) %>% # only those with use at baseline + 1 day or before
  filter(!(grepl("enox", CM_NAME, ignore.case = TRUE) & CM_DOSE == 40 & (CM_FREQ == 1 | CM_FREQ == 2))) %>%  # exclude low-dose proph. enoxa / but keep twice daily 40mg
  distinct(id_pat) %>% # only 1 entry per patient
  mutate(comed_acoa = 1)
# df_acoa %>% # keep the enoxa 40mg twice daily
#   select(id_pat, SUBJID_DER1, SUBJID_DER2, SUBJID_DER3, CM_NAME, CM_DOSE, CMDOSU, CM_FREQ, CM_FREQ_OTH, CM_ROUTE, CMROUTEOTH, CM_START, CM_END, randdate, cm_start_date, trt) %>%
#   View()
df <- left_join(df, df_acoa[, c("comed_acoa", "id_pat")], by = join_by(id_pat == id_pat)) # merge to main df
df <- df %>% 
  mutate(comed_acoa = case_when(is.na(comed_acoa) ~ 0,
                          TRUE ~ comed_acoa))
# addmargins(table(df$comed_acoa, df$trt, useNA = "always")) 

# INTERFERON
df_interferon <- df2 %>%
  filter(grepl("IFN|interf|SNG001", CM_NAME, ignore.case = TRUE)) # not a single case (check protocol)
df$comed_interferon <- 0 # see protocol
# unique(df_interferon$CM_NAME)
# df_interferon <- left_join(df_interferon, df[, c("randdate", "trt", "id_pat")], by = join_by(id_pat == id_pat))
# df_interferon$cm_start_date <- as.Date(df_interferon$CM_START, format = "%d/%m/%Y") 
# df_interferon <- df_interferon %>% 
#   mutate(cm_baseline = case_when(cm_start_date <= randdate + 1 ~ 1, TRUE ~ 0)) %>% 
#   filter(cm_baseline == 1) %>% # only those with use at baseline + 1 day or before
#   filter(!(grepl("enox", CM_NAME, ignore.case = TRUE) & CM_DOSE == 40 & (CM_FREQ == 1 | CM_FREQ == 2))) %>%  # exclude low-dose proph. enoxa / but keep twice daily 40mg
#   distinct(id_pat) %>% # only 1 entry per patient
#   mutate(comed_interferon = 1)
# # df_interferon %>% 
# #   select(id_pat, SUBJID_DER1, SUBJID_DER2, SUBJID_DER3, CM_NAME, CM_DOSE, CMDOSU, CM_FREQ, CM_FREQ_OTH, CM_ROUTE, CMROUTEOTH, CM_START, CM_END, randdate, cm_start_date, trt) %>%
# #   View()
# df <- left_join(df, df_interferon[, c("comed_interferon", "id_pat")], by = join_by(id_pat == id_pat)) # merge to main df
# df <- df %>% 
#   mutate(comed_interferon = case_when(is.na(comed_interferon) ~ 0,
#                           TRUE ~ comed_interferon))
# addmargins(table(df$comed_interferon, df$trt, useNA = "always")) 

# ANTIBIOTICS
# df2 %>% 
#   select(id_pat, SUBJID_DER1, SUBJID_DER2, SUBJID_DER3, CM_NAME, CM_DOSE, CMDOSU, CM_FREQ, CM_FREQ_OTH, CM_ROUTE, CMROUTEOTH, CM_START, CM_END) %>%
#   View()
df_ab <- df2 %>%
  filter(grepl("amox|peni|cefo|ceft|cefu|cipro|clar|clotr|trimox|doxy|fluc|genta|levoflo|merop|metronid|tazo|piper|vanco", CM_NAME, ignore.case = TRUE))
# unique(df_ab$CM_NAME)
df_ab <- left_join(df_ab, df[, c("randdate", "trt", "id_pat")], by = join_by(id_pat == id_pat))
df_ab$cm_start_date <- as.Date(df_ab$CM_START, format = "%d/%m/%Y") 
df_ab <- df_ab %>% 
  mutate(cm_baseline = case_when(cm_start_date <= randdate + 1 ~ 1, TRUE ~ 0)) %>% 
  filter(cm_baseline == 1) %>% # only those with use at baseline + 1 day or before
  distinct(id_pat) %>% # only 1 entry per patient
  mutate(comed_ab = 1)
df <- left_join(df, df_ab[, c("comed_ab", "id_pat")], by = join_by(id_pat == id_pat)) # merge to main df
df <- df %>% 
  mutate(comed_ab = case_when(is.na(comed_ab) ~ 0,
                          TRUE ~ comed_ab))
# addmargins(table(df$comed_ab, df$trt, useNA = "always")) 

# ANY OTHER COMEDICATION
df_comed_other <- df2 %>%
  filter(!is.na(CM_NAME))
# unique(df_comed_other$CM_NAME)
df_comed_other <- left_join(df_comed_other, df[, c("randdate", "trt", "id_pat", "comed_ab", "comed_acoa", "comed_dexa", "comed_rdv", "comed_toci", "comed_interferon")], by = join_by(id_pat == id_pat))
df_comed_other$cm_start_date <- as.Date(df_comed_other$CM_START, format = "%d/%m/%Y") 
df_comed_other <- df_comed_other %>% 
  mutate(cm_baseline = case_when(cm_start_date <= randdate + 1 ~ 1, TRUE ~ 0)) %>% 
  filter(cm_baseline == 1) %>% # only those with use at baseline + 1 day or before
  # filter(comed_ab == 0 & comed_acoa == 0 & comed_dexa == 0 & comed_rdv == 0 & comed_toci & comed_interferon == 0) %>% # to be discussed, participants often have several
  distinct(id_pat) %>% # only 1 entry per patient
  mutate(comed_other = 1)
df <- left_join(df, df_comed_other[, c("comed_other", "id_pat")], by = join_by(id_pat == id_pat)) # merge to main df
df <- df %>% 
  mutate(comed_other = case_when(is.na(comed_other) ~ 0,
                          TRUE ~ comed_other))
# addmargins(table(df$comed_other, df$trt, useNA = "always")) # to be discussed, participants often have several

## GROUP them for the subgroup analysis, according to protocol
df <- df %>% # there are no missings in comed_dexa and comed_toci
  mutate(comed_cat = case_when(comed_dexa == 0 & comed_toci == 0 ~ 1, # patients without Dexa nor Toci
                               comed_dexa == 1 & comed_toci == 1 ~ 2, # patients with Dexa and Toci
                               comed_dexa == 1 & comed_toci == 0 ~ 3, # patients with Dexa but no Toci
                               comed_dexa == 0 & comed_toci == 1 ~ 4)) # patients with Toci but no Dexa
# addmargins(table(df$comed_cat, df$trt, useNA = "always"))


### Comorbidities at baseline
df <- df %>% # 3 missing
  mutate(comorb_lung = case_when(MH_ASTHMA == 1 | MH_OBSTRUCT == 1 | MH_LUNGDISEASE == 1 | MH_INTERSTIT == 1 ~ 1,
                                 MH_ASTHMA == 0 & MH_OBSTRUCT == 0 & MH_LUNGDISEASE == 0 & MH_INTERSTIT == 0 ~ 0))
df <- df %>% # no missing
  mutate(comorb_liver = case_when(MH_LIVERDIS == 1 ~ 1,
                                  MH_LIVERDIS == 0 ~ 0))
df <- df %>% # 1 missing
  mutate(comorb_cvd = case_when(MH_HEARTD == 1 | MH_STROKE == 1 | MH_ISCHAEMIC == 1 | MH_ATRIALFIB == 1 | MH_OTHCARDIAC == 1 ~ 1,
                                MH_HEARTD == 0 & MH_STROKE == 0 & MH_ISCHAEMIC == 0 & MH_ATRIALFIB == 0 & MH_OTHCARDIAC == 0 ~ 0))
df <- df %>% # no missing
  mutate(comorb_aht = case_when(MH_HYPT == 1 ~ 1,
                                MH_HYPT == 0 ~ 0))
df <- df %>% # no missing
  mutate(comorb_dm = case_when(MH_DIABETES == 1 ~ 1,
                               MH_DIABETES == 0 ~ 0))
df <- df %>% # 3 missing
  mutate(comorb_obese = case_when(MH_OBESE == 1 ~ 1,
                               MH_OBESE == 0 ~ 0))
df <- df %>% # 5 missing
  mutate(comorb_smoker = case_when(MH_SMOKING == 2 ~ 1,
                               MH_SMOKING == 1 | MH_SMOKING == 3 ~ 0))
df <- df %>% # no missing
  mutate(comorb_kidney = case_when(MH_CHRONKIDND == 1 ~ 1,
                               MH_CHRONKIDND == 0 ~ 0))
df <- df %>% # 1 missing
  mutate(comorb_cancer = case_when(MH_CANCERPAST == 1 | MH_CURRCANC == 1 ~ 1,
                               MH_CANCERPAST == 0 & MH_CURRCANC == 0 ~ 0))
df <- df %>% # no missing
  mutate(comorb_autoimm = case_when(MH_AUTOIMM == 1 ~ 1,
                               MH_AUTOIMM == 0 ~ 0))
df <- df %>% # no missing
  mutate(immunosupp = case_when(MH_IMMUNODEF == 1 | MH_PRONETOINF == 1 ~ 1,
                               MH_IMMUNODEF == 0 & MH_PRONETOINF == 0 ~ 0))

df <- df %>% 
  mutate(any_comorb = case_when(comorb_lung == 1 | comorb_liver == 1 | comorb_cvd == 1 |
                                  comorb_aht == 1 | comorb_dm == 1 | comorb_obese == 1 | comorb_smoker == 1
                                | immunosupp == 1 | comorb_cancer == 1 | comorb_autoimm == 1 | comorb_kidney == 1 
                                  ~ 1,
                                comorb_lung == 0 & comorb_liver == 0 & comorb_cvd == 0 &
                                  comorb_aht == 0 & comorb_dm == 0 & comorb_obese == 0 & comorb_smoker == 0
                                & immunosupp == 0 & comorb_cancer == 0 & comorb_autoimm == 0 & comorb_kidney == 0
                                ~ 0))
# table(df$any_comorb, useNA = "always") # 4 missing

# the remaining 4 missing have only NA in 1 comorb category => no evidence for comorbidity -> recode as 0
# df %>%
#   select(id_pat, any_comorb, comorb_lung, comorb_liver, comorb_cvd, comorb_aht, comorb_dm, comorb_obese, comorb_smoker, immunosupp, comorb_kidney, comorb_autoimm, comorb_cancer) %>%
#   filter(is.na(any_comorb)) %>%
#   View()
df <- df %>% 
  mutate(any_comorb = case_when(is.na(any_comorb) ~ 0,
                                TRUE ~ any_comorb))

## group them for the subgroup analysis, according to protocol // count all pre-defined comorbidities per patient first
comorb <- df %>% 
  select(id_pat, comorb_lung, comorb_liver, comorb_cvd, comorb_aht, comorb_dm, comorb_obese, comorb_smoker, immunosupp, comorb_kidney, comorb_autoimm, comorb_cancer)
comorb$comorb_count <- NA
for (i in 1:dim(comorb)[[1]]) {
  comorb$comorb_count[i] <- ifelse(
    sum(comorb[i, ] %in% c(1)) > 0,
    sum(comorb[i, ] %in% c(1)),
    NA
  )
}
comorb <- comorb %>% 
  mutate(comorb_count = case_when(comorb_lung == 0 & comorb_liver == 0 & comorb_cvd == 0 &
                                  comorb_aht == 0 & comorb_dm == 0 & comorb_obese == 0 & comorb_smoker == 0
                                & immunosupp == 0 & comorb_cancer == 0 & comorb_autoimm == 0 & comorb_kidney == 0 ~ 0,
                                TRUE ~ comorb_count))
# the remaining 4 missing have only NA in 1 comorb category => no evidence for comorbidity -> recode as 0
comorb <- comorb %>% 
  mutate(comorb_count = case_when(is.na(comorb_count) ~ 0,
                                TRUE ~ comorb_count))
df <- left_join(df, comorb[, c("comorb_count", "id_pat")], by = join_by(id_pat == id_pat)) ## merge imputed variable back
df <- df %>% # same 4 missing
  mutate(comorb_cat = case_when(immunosupp == 1 ~ 4, # immunocompromised
                                comorb_count == 0 ~ 1, # no comorbidity
                                comorb_count == 1 ~ 2, # one comorbidity
                                comorb_count >1 & (immunosupp == 0 | is.na(immunosupp)) ~ 3)) # multiple comorbidities
table(df$comorb_cat, useNA = "always")
df <- df %>%
  mutate(comorb_any = case_when(comorb_count == 0 ~ 0, # no comorbidity
                                comorb_count >0 ~ 1)) # any comorbidity


### CRP at baseline
# summary(df$CRP, useNA = "always")
df$crp_date <- as.Date(df$CRP_DAT, format = "%d/%m/%Y") 
df_crp <- df %>% 
  mutate(crp_baseline = case_when(crp_date <= (randdate + 1) ~ 1, TRUE ~ 0)) %>% 
  filter(crp_baseline == 1) %>% 
  rename(crp = CRP)
df <- left_join(df, df_crp[, c("crp", "id_pat")], by = join_by(id_pat == id_pat)) ## merge to main df
# summary(df$crp, useNA = "always")
df %>% 
  drop_na(crp) %>% 
  ggplot(aes(x = crp)) +
  geom_density(fill = "blue", color = "black") +
  labs(title = "Density Plot of CRP",
       x = "CRP",
       y = "Density")


### Viremia / Undetectable VL at baseline
# transform all vl date variables
df$vl_baseline_date <- as.Date(df$COVID19_TSTRCNT, format = "%d/%m/%Y") 
df <- df %>% 
  mutate(vl_baseline_mark = case_when(vl_baseline_date <= (randdate + 1) ~ 1,
                                      vl_baseline_date > (randdate + 1) ~ 0)) # mark the baseline VL, if after baseline mark as 0, otherwise NA
# table(df$vl_baseline_mark) # double-check with trial team, for n=4 probably data entry error
df <- df %>% 
  mutate(vl_baseline = case_when(COVID19_POS == 0 ~ 1, # 1=pos / 0=neg=undetectable
                                 COVID19_POS == 1 ~ 0)) 


# date_columns <- c("COVID19_TSTRCNT", "COVID19_RECDAT", "COVID19_RECDAT1", "COVID19_RECDAT2", "COVID19_RECDAT3", "COVID19_RECDAT4", "COVID19_RECDAT5", "COVID19_RECDAT6", "COVID19_RECDAT7", "COVID19_RECDAT8")
# df <- df %>%
#   mutate_at(vars(date_columns), list(~ as.Date(., format = "%d/%m/%Y")))
# df <- df %>% # earliest should be COVID19_TSTRCNT, but just to be sure and take all available data into account
#   mutate(vl_earliest_date = pmin(COVID19_TSTRCNT, COVID19_RECDAT, COVID19_RECDAT1, COVID19_RECDAT2, COVID19_RECDAT3, COVID19_RECDAT4, COVID19_RECDAT5, COVID19_RECDAT6, COVID19_RECDAT7, COVID19_RECDAT8, na.rm = TRUE)) %>% 
#   mutate(vl_baseline_mark = case_when(vl_earliest_date <= (randdate + 1) ~ 1)) %>% # mark the baseline VL, otherwise NA
#   mutate(vl_baseline_ori = case_when(vl_baseline_mark == 1 & !is.na(COVID19_TSTRCNT) & COVID19_TSTRCNT < COVID19_RECDAT ~ COVID19_RESULT,
#                                  vl_baseline_mark == 1 & is.na(COVID19_TSTRCNT) & !is.na(COVID19_RECDAT) & COVID19_RECDAT < COVID19_RECDAT1 ~ COVID19_RESULT1,
#                                  vl_baseline_mark == 1 & is.na(COVID19_TSTRCNT) & is.na(COVID19_RECDAT) & !is.na(COVID19_RECDAT1) & COVID19_RECDAT1 < COVID19_RECDAT2 ~ COVID19_RESULT2,
#                                  vl_baseline_mark == 1 & is.na(COVID19_TSTRCNT) & is.na(COVID19_RECDAT) & is.na(COVID19_RECDAT1) & !is.na(COVID19_RECDAT2) & COVID19_RECDAT2 < COVID19_RECDAT3 ~ COVID19_RESULT3,
#                                  vl_baseline_mark == 1 & is.na(COVID19_TSTRCNT) & is.na(COVID19_RECDAT) & is.na(COVID19_RECDAT1) & is.na(COVID19_RECDAT2) & !is.na(COVID19_RECDAT3) & COVID19_RECDAT3 < COVID19_RECDAT4 ~ COVID19_RESULT4,
#                                  vl_baseline_mark == 1 & is.na(COVID19_TSTRCNT) & is.na(COVID19_RECDAT) & is.na(COVID19_RECDAT1) & is.na(COVID19_RECDAT2) & is.na(COVID19_RECDAT3) & !is.na(COVID19_RECDAT4) & COVID19_RECDAT4 < COVID19_RECDAT5 ~ COVID19_RESULT5,
#                                  )) %>% 
#   mutate(vl_baseline = case_when(vl_baseline_ori == 0 ~ 1, # 1=pos / 0=neg=undetectable
#                                  vl_baseline_ori == 1 ~ 0)) 
# df %>% 
#   select(id_pat, randdate, vl_baseline_mark, vl_baseline, COVID19_TSTRCNT, COVID19_RESULT, 
#                               COVID19_RECDAT, COVID19_RESULT1,
#                               COVID19_RECDAT1, COVID19_RESULT2,
#                               COVID19_RECDAT2, COVID19_RESULT3,
#                               COVID19_RECDAT3, COVID19_RESULT4,
#          COVID19_RECDAT4, COVID19_RESULT5,
#          COVID19_RECDAT5, COVID19_RECDAT6, COVID19_RECDAT7, COVID19_RECDAT8) %>%
#   View()


### Serology at baseline // not available
### COVID-19 vaccination at baseline // not available
### Variant // not available

```
Discussion points:

# Endpoints
```{r echo=TRUE}
# transform all resp scores
point7_transform <- function(df, clinstatus_var, pos_var) {
  df <- df %>%
    mutate({{ clinstatus_var }} :=
             case_when({{ pos_var }} %in% c(6, 7) ~ 1,
                       {{ pos_var }} == 5 ~ 2,
                       {{ pos_var }} == 4 ~ 3,
                       {{ pos_var }} == 3 ~ 4,
                       {{ pos_var }} == 2 ~ 5,
                       {{ pos_var }} == 1 ~ 6)) %>%
    mutate({{ clinstatus_var }} := factor({{ clinstatus_var }}, levels = 1:6))
}
df <- point7_transform(df, clinstatus_1, POINT7_OS_POS1) ## POINT7_OS_POS1 = D2 = clinstatus_1 (1 day after clinstatus_baseline) / D1 = baseline/randomization day
df <- point7_transform(df, clinstatus_2, POINT7_OS_POS2)
df <- point7_transform(df, clinstatus_3, POINT7_OS_POS3)
df <- point7_transform(df, clinstatus_4, POINT7_OS_POS4)
df <- point7_transform(df, clinstatus_5, POINT7_OS_POS5)
df <- point7_transform(df, clinstatus_6, POINT7_OS_POS6) 
df <- point7_transform(df, clinstatus_7, POINT7_OS_POS7)
df <- point7_transform(df, clinstatus_8, POINT7_OS_POS8)
df <- point7_transform(df, clinstatus_9, POINT7_OS_POS9)

status_columns <- grep("^PART_STATUS", names(df), value = TRUE)
withdraw_columns <- grep("^CONSENT_CONT", names(df), value = TRUE)
discharge_columns <- grep("^VISIT_DISCHARGE", names(df), value = TRUE)

df %>% 
  select(id_pat,
         contains("RESP_DELIVER"), # RESP_DELIVER3 = D2 = POINT7_OS_POS1 = clinstatus_1 // corresponds well
         contains("clinstatus_"),
         contains("PART_STATUS"),
         # contains("VISIT_DAY"), # does not any info
         # contains("VISIT_TYPE"), # does not contain more info
         # contains("CONSENT_CONT"),
         contains("VISIT_DISCHARGE"),
         ) %>%
  # filter(is.na(clinstatus_1)) %>% # RESP_DELIVER3 and onwards unfortunately also missing if clinstatus_1 and onwards missing
  # PART_STATUS (alive/dead) and onwards unfortunately also missing if clinstatus_1 and onwards missing
  # filter_at(vars(status_columns), any_vars(. == 0)) %>% # PART_STATUSx (alive=1/dead=0) corresponds well with clinstatus_ (PART_STATUS2 = clinstatus_1) and does not contain more info - except id 590013 -> died at baseline?
  # filter_at(vars(withdraw_columns), any_vars(. == 1)) %>% # CONSENT_CONTx (withdrew=1) corresponds well with NA in clinstatus_ (CONSENT_CONT2 = clinstatus_1) and does not contain more info
  filter_at(vars(discharge_columns), any_vars(. == 1)) %>% # VISIT_DISCHARGEx (discharged=1) corresponds well with score in clinstatus_ (VISIT_DISCHARGE2 = clinstatus_1) - except 020040 -> discharged with NIV?
  View()

df %>% 
  filter(id_pat == "590013") %>% 
  View()

# => 1) find out about 590013, 2) use PART_STATUS == 0 to count deaths and clinstatus_ for time to death, 3) use CONSENT_CONTx to mark withdrawals and time to withdrawal (CONSENT_CONT2 = clinstatus_1 = time to withdrawal = 1 day), 4) use VISIT_DISCHARGEx to mark discharge and time to discharge (VISIT_DISCHARGE2 = clinstatus_1, i.e. time to discharge = 1 day)

# Add info from df2:
df2$death_date <- as.Date(df2$DATE_DEATH, format = "%d/%m/%Y") # unique entries (distinct(id_pat))
df2$withdraw_date <- as.Date(df2$CONS_WITHDAT, format = "%d/%m/%Y") # unique entries (distinct(id_pat))
df2 <- df2 %>% 
  mutate(lastvisit = case_when(EOS_LV == "2" ~ "baseline",
                               EOS_LV == "DIS1" ~ "discharge",
                               TRUE ~ EOS_LV)) # unique entries (distinct(id_pat)), missing for 11
df2 <- df2 %>% 
  mutate(lastvisit_status = case_when(EOS_LV == "2" ~ "baseline",
                               EOS_LV == "DIS1" ~ "discharge",
                               TRUE ~ EOS_LV)) # unique entries (distinct(id_pat)), missing for 11

table(df2$EOS_RSN)
df_death <- df2 %>% 
  filter(!is.na(death_date)) %>% 
  distinct(id_pat)


df2 %>%
  select(id_pat, death_date, CONS_WITHDAT, EOS_LV, EOS_RSN, TREAT_CESSATION, TREAT_CESS_RSN, everything()) %>% 
  View()

investigate:
CONS_WITHDAT
EOS_LV
EOS_RSN
TREAT_CESS 
TREAT_CESS_RSN == 5 = withdrawal
TREAT_CESSATION


# Filter the dataframe if any of the PART_STATUS columns is equal to 0
filtered_df <- df %>%
  filter_at(vars(part_status_columns), any_vars(. == 0))


# time to event data
df$death_d <- as.numeric(df$deathdated1_DROP - df$randdate) 
df$discharge_d <- as.numeric(df$visitdated1_DISCH - df$randdate)
df$withdraw_d <- as.numeric(df$withdrawdated1_DROP - df$randdate)
df$withdrawi_d <- as.numeric(df$invdecisdated1_DROP - df$randdate)
# df$ltfu_d <- as.numeric(df$ltfudated1_DROP - df$randdate) ## there were no LTFU
df$readmission_d <- as.numeric(df$readmdate - df$randdate)
df$maxfup_d <- as.numeric(df$lastdate - df$randdate)



# (i) Primary outcome: Mortality at day 28
df <- df %>% # 12 have no outcome data and withdrew or were withdrawn, but have clinstatus_baseline and fup clinstatus data 
  mutate(mort_28 = case_when(death_d <29 ~ 1,
                             discharge_d <29 ~ 0, # all discharged were discharged alive and not to hospice
                             clinstatus_28 %in% c(2,3,4,5) ~ 0, # still at hospital but alive
                             discharge_d >28 ~ 0)) # discharged later, proof of still alive
# df %>%
#   select(mort_28, clinstatus_baseline, clinstatus_2, clinstatus_4, clinstatus_7, clinstatus_14, clinstatus_21, clinstatus_28, clinstatus_35) %>%
#   filter(is.na(mort_28)) %>%
#   View()

# First, keep mort_28 as complete case

# Second, use multiple imputation (see below)

# Third, apply a deterministic imputation (see notes): we use the same rules as ACTT2 => No transfer to hospice happened in bari-solidact -> assign "alive"
df <- df %>%
  mutate(mort_28_dimp = case_when(is.na(mort_28) ~ 0,
                             TRUE ~ c(mort_28)))


# (ii) Mortality at day 60
df <- df %>% # same 12 that have no outcome data and withdrew or were withdrawn -> see above
  mutate(mort_60 = case_when(death_d <61 ~ 1,
                             discharge_d <61 ~ 0, # all discharged were discharged alive and not to hospice
                             clinstatus_35 %in% c(2,3,4,5) ~ 0, # still at hospital but alive
                             discharge_d >60 ~ 0)) # discharged later, proof of still alive


# (iii) Time to death within max. follow-up time 
df$death_reached <- df$death_yn # do not bother about missings in mort_28
df <- df %>% # 2 are left without any time to event data => impute max. follow-up time
  mutate(death_time = case_when(death_d >=0 ~ c(death_d), # time to death, if no time to death, then...
                                discharge_d >=0 & (is.na(withdraw_d) | withdraw_d >28) & (is.na(withdrawi_d) | withdrawi_d >28) ~ 28, # 28d for all those who were discharged alive and not withdrawn before, then...
                                discharge_d >= withdraw_d ~ c(discharge_d), # time to discharge if this was greater than time to withdrawal
                                discharge_d >= withdrawi_d ~ c(discharge_d), # see above
                                maxfup_d >=0 & is.na(withdraw_d) & is.na(withdrawi_d) ~ c(maxfup_d), # max fup for the remaining ones not withdrawn
                                withdraw_d >=0 ~ c(withdraw_d), # time to withdrawal for those withdrawn (and not discharged before)
                                withdrawi_d >=0 ~ c(withdrawi_d))) # time to investigator withdrawal for those inv-withdrawn (and not discharged before)

# (iv) New mechanical ventilation among survivors within 28 days. Bari-Solidact only included clinstatus 4 and 5.
df <- df %>% # The NAs are not eligible (died or clinstatus_baseline == 5) and thus are excluded from denominator
  mutate(new_mv_28 = case_when(clinstatus_baseline == 4 & (mort_28 == 0 | is.na(mort_28)) 
                               & (clinstatus_2 == 5 | clinstatus_4 == 5 | clinstatus_7 == 5 | clinstatus_14 == 5 
                                  | clinstatus_21 == 5 | clinstatus_28 == 5)
                               ~ 1,
                               clinstatus_baseline == 4 & mort_28 == 0
                               ~ 0))
# (iv) Alternative definition/analysis: New mechanical ventilation OR death within 28 days => include all in denominator.
df <- df %>% # no missing
  mutate(new_mvd_28 = case_when(new_mv_28 == 1 | mort_28 == 1 ~ 1,
                                new_mv_28 == 0 | mort_28 == 0 ~ 0))
# table(df$new_mvd_28, useNA = "always") # 11 missing


# (v) Clinical status at day 28
df <- df %>% # Adapt clinstatus_28, since currently excluding those discharged or died or missing data.
  mutate(clinstatus_28 = case_when(clinstatus_28 == 6 ~ 6,
                                   clinstatus_28 == 5 ~ 5,
                                   clinstatus_28 == 4 ~ 4,
                                   clinstatus_28 == 3 ~ 3,
                                   clinstatus_28 == 2 ~ 2,
                                   clinstatus_28 == 1 ~ 1,
                                   mort_28 == 1 ~ 6, # died within 28d
                                   discharge_d <29 ~ 1 # discharged alive / reached discharge criteria within 28d
                                   )) 
df$clinstatus_28 <- factor(df$clinstatus_28, levels = 1:6) # 18 missing -> for some I know they did not die, but I don't know exact clinicalstatus -> LOVCF
# table(df$clinstatus_28, useNA = "always")
# df %>%
#   select(mort_28, clinstatus_baseline, clinstatus_2, clinstatus_4, clinstatus_7, clinstatus_14, clinstatus_21, clinstatus_28, clinstatus_35) %>%
#   filter(is.na(clinstatus_28)) %>%
#   View()

## Imputation according to protocol: If there was daily data for the ordinal score available but with missing data for single days, then we carried last observed value forward unless for day 28, whereby we first considered data from the window (+/-3 days) -> no window data in Bari-Solidact => LVCF
dfcs <- df %>% 
    select(id_pat, clinstatus_baseline, clinstatus_2, clinstatus_4, clinstatus_7, clinstatus_14, clinstatus_21, clinstatus_28)
impute_last_forw = function(df){
  first = which(names(df)%in%c("clinstatus_baseline"))
  last = which(names(df)%in%c("clinstatus_28"))
  for (i in 1:dim(df)[[1]]){
    for (j in first[1]:last[1]){
      p = df[i, j]
      df[i,j] <- 
        ifelse(!is.na(df[i, j]), p, df[i, j-1])
    }
  }
  df
}
dfcs <- impute_last_forw(dfcs)
dfcs <- dfcs %>% # To control, don't overwrite
  rename(clinstatus_28_imp = clinstatus_28)
df <- left_join(df, dfcs[, c("clinstatus_28_imp", "id_pat")], by = join_by(id_pat == id_pat)) ## Merge imputed variable back // re-admissions already correctly incorporated
# table(df$clinstatus_28_imp, useNA = "always")

# (vi) Time to discharge or reaching discharge criteria up to day 28 // Patients who died prior to day 28 are assumed not having reached discharge, i.e. counted as 28 days. 
df <- df %>% 
  mutate(discharge_reached = case_when(discharge_d <29 ~ 1,
                                       TRUE ~ 0))
df <- df %>% # 2 are left without any time to event data => impute max. follow-up time
  mutate(discharge_time = case_when(discharge_d >=0 & (is.na(withdraw_d) | withdraw_d >28) & (is.na(withdrawi_d) | withdrawi_d >28) ~ c(discharge_d), # time to discharge in case no withdrawal or withdrawal after 28d. If no time to discharge, then...
                                    death_d >=0 ~ c(death_d), # time to death, then...
                                    discharge_d >= withdraw_d ~ c(discharge_d), # add time to discharge where time to discharge is after time to withdrawal 
                                    discharge_d >= withdrawi_d ~ c(discharge_d), # see above
                                    maxfup_d >=0 & is.na(withdraw_d) & is.na(withdrawi_d) ~ c(maxfup_d), # max fup for the remaining ones not withdrawn
                                withdraw_d >=0 ~ c(withdraw_d), # time to withdrawal for those withdrawn (and not discharged before)
                                withdrawi_d >=0 ~ c(withdrawi_d))) # time to investigator withdrawal for those inv-withdrawn (and not discharged before)
df <- df %>% # restrict to max fup time 28d
  mutate(discharge_time = case_when(discharge_time >28 ~ 28,
                                    TRUE ~ discharge_time))
df <- df %>% # add 28d for those that died - as a sens-variable
  mutate(discharge_time_sens = case_when(mort_28 == 1 ~ 28,
                                    TRUE ~ discharge_time))

# (vi) Sens-analysis: Alternative definition/analysis of outcome: time to sustained discharge within 28 days
df <- df %>% # there are 6 re-admissions: the one readmitted at day 16 was re-discharged before day ?28?. The ones at d21 & d27 not. And then there are 3 that were readmitted later than d28 => Reclassify d21 and d27 and add 28d, add d20 to the one re-admitted at d16.
  mutate(discharge_reached_sus = case_when(readmission_d == 21 | readmission_d == 27 ~ 0,
                                           TRUE ~ discharge_reached))
df <- df %>%
  mutate(discharge_time_sus = case_when(readmission_d == 16 ~ 20,
                                        readmission_d == 21 | readmission_d == 27 ~ 28,
                                        TRUE ~ discharge_time))


# (vii) Viral clearance up to day 5, day 10, and day 15 (Viral load value <LOQ and/or undectectable)
df$vir_clear_5 <- df$vloqundet_yn_D3
df <- df %>% 
  mutate(vir_clear_10 = case_when(vloqundet_yn_D8 == 1 ~ 1,
                                  vir_clear_5 == 1 & is.na(vloqundet_yn_D8) ~ 1,
                                  vloqundet_yn_D8 == 0 ~ 0,
                                  vir_clear_5 == 0 & is.na(vloqundet_yn_D8) ~ 0))
df <- df %>% 
  mutate(vir_clear_15 = case_when(vloqundet_yn_D15 == 1 ~ 1,
                                  vir_clear_10 == 1 & is.na(vloqundet_yn_D15) ~ 1,
                                  vloqundet_yn_D15 == 0 ~ 0,
                                  vir_clear_10 == 0 & is.na(vloqundet_yn_D15) ~ 0))


# (viii) Quality of life at day 28 // detailed measures available - wait for other trials first


# (ix) Participants with an adverse event grade 3 or 4, or a serious adverse event, excluding death, by day 28
# table(df_ae$AE_28) # any grade 3 or 4 or serious
df_ae34 <- df_ae %>% 
  rename(id_pat = PARTICIPANT_ID) %>% 
  filter(AE_28 == 1) # contains only grade 3 or 4
# Keep just 1 id_pat (-> ANY adverse event grade 3 (severe), 4 (serious)) 
df_ae34_unique <- df_ae34 %>% distinct(id_pat, .keep_all = TRUE)
# Assign the outcome
df_ae34_unique$ae_28 <- 1
# table(df_ae34_unique$ae_28)
# merge
df <- left_join(df, df_ae34_unique[, c("ae_28", "id_pat")], by = join_by(id_pat == id_pat)) ## merge variable to main df
# the remaining missing have no AE grade 34 -> recode as 0 and exclude deaths
df <- df %>% 
  mutate(ae_28 = case_when(is.na(ae_28) ~ 0, # the LTFU were discharged
                           mort_28 == 1 ~ NA, # exclude the deaths
                                TRUE ~ ae_28))
# table(df$ae_28, df$mort_28, useNA = "always")
# addmargins(table(df$ae_28, df$trt, useNA = "always"))

# (ix) Sens-analysis: Alternative definition/analysis of outcome: incidence rate ratio (Poisson regression) -> AE per person by d28
ae_npp <- df_ae %>%
  rename(id_pat = PARTICIPANT_ID) %>%
  filter(AE_28 == 1) %>% 
  group_by(id_pat)%>%  
  summarise(ae_28_sev = n())
df <- left_join(df, ae_npp[, c("ae_28_sev", "id_pat")], by = join_by(id_pat == id_pat)) # merge variable to main df
# the remaining missing have no AE grade 34 -> recode as 0 and exclude deaths
df <- df %>% 
  mutate(ae_28_sev = case_when(is.na(ae_28_sev) ~ 0, # the LTFU were discharged
                           mort_28 == 1 ~ NA, # exclude the deaths
                                TRUE ~ ae_28_sev))
# addmargins(table(df$ae_28_sev, df$trt, useNA = "always"))

# (x) Adverse events of special interest within 28 days: a) thromboembolic events (venous thromboembolism, pulmonary embolism, arterial thrombosis), b) secondary infections (bacterial pneumonia including ventilator-associated pneumonia, meningitis and encephalitis, endocarditis and bacteremia, invasive fungal infection including pulmonary aspergillosis), c) Reactivation of chronic infection including tuberculosis, herpes simplex, cytomegalovirus, herpes zoster and hepatitis B, d) serious cardiac events (excl. hypertension), e) events related to signs of bone marrow suppression (anemia, lymphocytopenia, thrombocytopenia, pancytopenia), f) malignancy, g) gastrointestinal perforation (incl. gastrointestinal bleeding/diverticulitis), h) liver dysfunction/hepatotoxicity (grade 3 and 4), i) Multiple organ dysfunction syndrome and septic shock

a<-as.data.frame(unique(df_ae$MeddraPT)) # contains standardized categories
# unique(df_ae$MeddraLLT) 
# df_ae <- df_ae %>% 
#   mutate(dupl = duplicated(MeddraLLT, MeddraPT))
# df_ae %>% 
#   select(dupl, MeddraPT, MeddraLLT) %>% 
#   filter(dupl == F) %>% 
#   View() # does not contain more information

df_ae <- df_ae %>%
  rename(id_pat = PARTICIPANT_ID,
         trt = arm)
df_thrombo <- df_ae %>% # a) thromboembolic events (venous thromboembolism, pulmonary embolism, arterial thrombosis)
  filter(MeddraPT %in% c("Pulmonary embolism", "Cerebral infarction", "Vena cava thrombosis", "Deep vein thrombosis", "Catheter site thrombosis", "Peripheral artery thrombosis")) %>% 
  mutate(aesi = "thrombo")
df_sec_inf <- df_ae %>% # b) secondary infections (bacterial pneumonia including ventilator-associated pneumonia, meningitis and encephalitis, endocarditis and bacteremia, invasive fungal infection including pulmonary aspergillosis), but not COVID-19 pneumonia! First extract all infections, then reclassify.
  filter(MeddraPT %in% c("Pneumonia bacterial", "Pneumonia", # these are all ventilator-associated pneumonia not covid-19
                         "Septic arthritis staphylococcal", "Mediastinitis", "Pneumonitis", "Infectious pleural effusion",
                         "Superinfection bacterial", "Staphylococcal bacteraemia", "Bacterial infection", "Bacterial infection",
                         "Bacteraemia", "Fungaemia", "Disseminated aspergillosis", "URINARY TRACT INFECTION", "PYELONEPHRITIS", 
                         "Device related bacteraemia", "SEPSIS", "Sepis", "FUNGAL INFECTION", "ORAL CANDIDIASIS", 
                         "CANDIDA INFECTION","BRONCHOPULMONARY ASPERGILLOSIS", "VULVOVAGINAL MYCOTIC INFECTION", 
                         "FUNGAL SKIN INFECTION", "TOOTH INFECTION", "PAROTITIS", "CELLULITIS", "ORAL FUNGAL INFECTION",
                         "Bronchopulmonary aspergillosis", "Prostatitis Escherichia coli", "ABDOMINAL INFECTION", 
                         "Candida pneumonia", "PHLEBITIS", "CANDIDA PNEUMONIA", "BURSITIS", "CHOLECYSTITIS ACUTE")) %>% 
  mutate(aesi = "sec_inf")
df_reactivate <- df_ae %>% # c) Reactivation of chronic infection including tuberculosis, herpes simplex, cytomegalovirus, herpes zoster and hepatitis B.
  filter(MeddraPT %in% c("Herpes simplex reactivation", "Herpes simplex", "Cytomegalovirus infection reactivation", "Hepatitis B reactivation")) %>% 
  mutate(aesi = "reactivate")
df_cardiac <- df_ae %>% # d) serious cardiac events (excl. not hypertension)
  filter(MeddraPT %in% c("BRADYCARDIA", "Cardiac failure", "Bradycardia", "Acute myocardial infarction", 
                         "SUPRAVENTRICULAR TACHYCARDIA", "TACHYCARDIA", "VENTRICULAR EXTRASYSTOLES", "ATRIAL FIBRILLATION", 
                         "Acute coronary syndrome","Cardiac arrest", "SINUS ARRHYTHMIA")) %>% 
  mutate(aesi = "cardiac")
df_penia <- df_ae %>% # e) events related to signs of bone marrow suppression (anemia, lymphocytopenia, thrombocytopenia, pancytopenia)
  filter(MeddraPT %in% c("Anaemia", "LYMPHOCYTE COUNT DECREASED", "BLOOD CREATININE DECREASED", "THROMBOCYTOPENIA",
                         "LYMPHOPENIA", "LEUKOPENIA", "NEUTROPENIA", "Thrombocytopenia", "Bicytopenia")) %>% 
  mutate(aesi = "penia")
# df_malig <- NA
df_git_bl <- df_ae %>% # g) gastrointestinal perforation (incl. gastrointestinal bleeding/diverticulitis)
  filter(MeddraPT %in% c("Gastrointestinal haemorrhage", "Rectal haemorrhage", "ABDOMINAL WALL HAEMORRHAGE", "DIVERTICULUM GASTRIC")) %>% 
  mutate(aesi = "git_bl")
df_hepatox <- df_ae %>% # h) liver dysfunction/hepatotoxicity (grade 3 and 4)
  filter(MeddraPT %in% c("Hepatotoxicity", "Hepatocellular injury") |
           (MeddraPT %in% c("HEPATIC ENZYME INCREASED", "ALANINE AMINOTRANSFERASE INCREASED", "HYPERTRANSAMINASAEMIA",
                         "Alanine aminotransferase increased", "TRANSAMINASES INCREASED", "Transaminases increased",
                         "Aspartate aminotransferase increased", "Blood bilirubin increased") & 
              AE_28 == 1)) %>% # only grade 3 and 4 for the liver function tests
  mutate(aesi = "hepatox")
df_mods <- df_ae %>% # i) Multiple organ dysfunction syndrome and septic shock
  filter(MeddraPT %in% c("Multiple organ dysfunction syndrome", "Septic shock")) %>% 
  mutate(aesi = "mods")

df_aesi <- rbind(df_mods, df_hepatox, df_git_bl, df_penia, df_cardiac, df_reactivate, df_sec_inf, df_thrombo)
df_aesi <- df_aesi %>% rename(desc = MeddraPT)
df_aesi <- df_aesi %>% 
  select(trt, aesi, desc)
table(df_aesi$trt, df_aesi$aesi)
# Save
saveRDS(df_aesi, file = "df_aesi_barisolidact.RData")

# (xi) Adverse events, any grade and serious adverse event, excluding death, within 28 days, grouped by organ classes
df_ae <- df_ae %>% 
  select(trt, MeddraLLT, MeddraPT, MeddraSOC, Grade)
# Save
saveRDS(df_ae, file = "df_ae_barisolidact.RData")

```
Discussion points OUTCOME data:


